// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABn1C0I5GtOYp4pkJpsGCMF5QJwAlOTOw',
    appId: '1:924393294620:web:cd06cb314fdaaeb65088d9',
    messagingSenderId: '924393294620',
    projectId: 'kisankit-a98db',
    authDomain: 'kisankit-a98db.firebaseapp.com',
    storageBucket: 'kisankit-a98db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5qBZKXNGE4H1yclNrd3raFpTeOBVDhs',
    appId: '1:924393294620:android:54eb65344eba71b15088d9',
    messagingSenderId: '924393294620',
    projectId: 'kisankit-a98db',
    storageBucket: 'kisankit-a98db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApLRiDBUSpaFi_rknQZJ1cSql8Pd224Sg',
    appId: '1:924393294620:ios:7dcc9c2aafddb40c5088d9',
    messagingSenderId: '924393294620',
    projectId: 'kisankit-a98db',
    storageBucket: 'kisankit-a98db.firebasestorage.app',
    iosClientId: '924393294620-ufoqep61khtpct9s3pm7458haeqh7phk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisankit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApLRiDBUSpaFi_rknQZJ1cSql8Pd224Sg',
    appId: '1:924393294620:ios:7dcc9c2aafddb40c5088d9',
    messagingSenderId: '924393294620',
    projectId: 'kisankit-a98db',
    storageBucket: 'kisankit-a98db.firebasestorage.app',
    iosClientId: '924393294620-ufoqep61khtpct9s3pm7458haeqh7phk.apps.googleusercontent.com',
    iosBundleId: 'com.example.kisankit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABn1C0I5GtOYp4pkJpsGCMF5QJwAlOTOw',
    appId: '1:924393294620:web:1775c5ae20d53f895088d9',
    messagingSenderId: '924393294620',
    projectId: 'kisankit-a98db',
    authDomain: 'kisankit-a98db.firebaseapp.com',
    storageBucket: 'kisankit-a98db.firebasestorage.app',
  );
}
